import type { PermissionName } from '@/types'
import type { SettingsNavItem } from '../types'

export const SETTINGS_NAV: SettingsNavItem[] = [
  {
    id: 'overview',
    label: 'Overview',
    description: 'Configuration categories hub',
    path: '/settings',
    icon: 'LayoutGrid',
    group: 'system',
    permission: 'settings.view',
  },
  {
    id: 'company',
    label: 'Company',
    description: 'Legal identity, contacts, and address',
    path: '/settings/company',
    icon: 'Building2',
    group: 'organization',
    permission: ['settings.view', 'company.manage'],
    summaryKey: 'company',
  },
  {
    id: 'organization',
    label: 'Organization',
    description: 'Company structure overview',
    path: '/settings/organization',
    icon: 'Network',
    group: 'organization',
    permission: ['settings.view', 'organization.manage'],
  },
  {
    id: 'departments',
    label: 'Departments',
    description: 'Department codes, heads, and status',
    path: '/settings/departments',
    icon: 'Folders',
    group: 'organization',
    permission: ['department.view', 'department.manage', 'settings.view'],
    summaryKey: 'departments',
  },
  {
    id: 'designations',
    label: 'Designations',
    description: 'Job titles and levels',
    path: '/settings/designations',
    icon: 'BadgeCheck',
    group: 'organization',
    permission: ['designation.view', 'designation.manage', 'settings.view'],
    summaryKey: 'designations',
  },
  {
    id: 'locations',
    label: 'Locations',
    description: 'Offices and work sites',
    path: '/settings/locations',
    icon: 'MapPin',
    group: 'organization',
    permission: ['location.manage', 'settings.view'],
    summaryKey: 'locations',
  },
  {
    id: 'work-schedules',
    label: 'Work Schedules',
    description: 'Shifts, grace period, overtime',
    path: '/settings/work-schedules',
    icon: 'Clock3',
    group: 'hr',
    permission: ['schedule.manage', 'settings.view'],
    summaryKey: 'workSchedules',
  },
  {
    id: 'holidays',
    label: 'Holidays',
    description: 'Public and company holidays',
    path: '/settings/holidays',
    icon: 'CalendarDays',
    group: 'hr',
    permission: ['holiday.manage', 'settings.view'],
    summaryKey: 'holidays',
  },
  {
    id: 'leave-policies',
    label: 'Leave Policies',
    description: 'Allocations and carry forward',
    path: '/settings/leave-policies',
    icon: 'Palmtree',
    group: 'hr',
    permission: ['leave-policy.manage', 'settings.view'],
    summaryKey: 'leavePolicies',
  },
  {
    id: 'attendance',
    label: 'Attendance',
    description: 'Methods, thresholds, auto-absent',
    path: '/settings/attendance',
    icon: 'ClipboardCheck',
    group: 'hr',
    permission: ['attendance-settings.manage', 'settings.view'],
    summaryKey: 'attendance',
  },
  {
    id: 'payroll',
    label: 'Payroll',
    description: 'Frequency, rounding, tax flags',
    path: '/settings/payroll',
    icon: 'Wallet',
    group: 'payroll',
    permission: ['payroll-settings.manage', 'payroll.settings.manage', 'settings.view'],
    summaryKey: 'payroll',
  },
  {
    id: 'payslip',
    label: 'Payslip',
    description: 'Number format, sections, footer',
    path: '/settings/payslip',
    icon: 'FileText',
    group: 'payroll',
    permission: ['payslip-settings.manage', 'settings.view'],
    summaryKey: 'payslip',
  },
  {
    id: 'localization',
    label: 'Localization',
    description: 'Currency, date/time, timezone',
    path: '/settings/localization',
    icon: 'Globe2',
    group: 'system',
    permission: ['localization.manage', 'settings.view'],
    summaryKey: 'localization',
  },
  {
    id: 'notifications',
    label: 'Notifications',
    description: 'Default in-app notification toggles',
    path: '/settings/notifications',
    icon: 'Bell',
    group: 'system',
    permission: ['notification-settings.manage', 'notification.settings.manage', 'settings.view'],
    summaryKey: 'notifications',
  },
  {
    id: 'workflows',
    label: 'Workflows',
    description: 'Default approvers and fallback',
    path: '/settings/workflows',
    icon: 'GitBranch',
    group: 'system',
    permission: ['workflow-settings.manage', 'settings.view'],
    summaryKey: 'workflow',
  },
  {
    id: 'branding',
    label: 'Branding',
    description: 'Logo and brand colors',
    path: '/settings/branding',
    icon: 'Palette',
    group: 'system',
    permission: ['branding.manage', 'settings.view'],
    summaryKey: 'branding',
  },
  {
    id: 'audit',
    label: 'Audit',
    description: 'Settings change history',
    path: '/settings/audit',
    icon: 'ScrollText',
    group: 'system',
    permission: ['settings.view', 'security.view'],
  },
]

export function canAccessSettingsNav(
  item: SettingsNavItem,
  hasPermission: (p: PermissionName | PermissionName[]) => boolean,
): boolean {
  return hasPermission(item.permission)
}

export const WEEKDAY_OPTIONS = [
  { value: 'monday', label: 'Monday' },
  { value: 'tuesday', label: 'Tuesday' },
  { value: 'wednesday', label: 'Wednesday' },
  { value: 'thursday', label: 'Thursday' },
  { value: 'friday', label: 'Friday' },
  { value: 'saturday', label: 'Saturday' },
  { value: 'sunday', label: 'Sunday' },
] as const

export const TIMEZONE_OPTIONS = [
  { value: 'UTC', label: 'UTC' },
  { value: 'Asia/Kolkata', label: 'Asia/Kolkata' },
  { value: 'Asia/Dubai', label: 'Asia/Dubai' },
  { value: 'Asia/Singapore', label: 'Asia/Singapore' },
  { value: 'Europe/London', label: 'Europe/London' },
  { value: 'America/New_York', label: 'America/New_York' },
  { value: 'America/Los_Angeles', label: 'America/Los_Angeles' },
] as const

export const DATE_FORMAT_OPTIONS = [
  { value: 'dd/MM/yyyy', label: 'DD/MM/YYYY' },
  { value: 'MM/dd/yyyy', label: 'MM/DD/YYYY' },
  { value: 'yyyy-MM-dd', label: 'YYYY-MM-DD' },
  { value: 'dd MMM yyyy', label: 'DD MMM YYYY' },
] as const
