import type { NavigationItem } from '@/types'
import { PERMISSIONS } from './permissions'

export const NAVIGATION_ITEMS: NavigationItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    path: '/dashboard',
    icon: 'LayoutDashboard',
    requiredPermission: PERMISSIONS.DASHBOARD_VIEW,
  },
  {
    id: 'employees',
    label: 'Employees',
    path: '/employees',
    icon: 'Users',
    module: 'Module 5',
    requiredPermission: PERMISSIONS.EMPLOYEE_VIEW,
  },
  {
    id: 'departments',
    label: 'Departments',
    path: '/departments',
    icon: 'Building2',
    module: 'Module 5',
    requiredPermission: PERMISSIONS.DEPARTMENT_VIEW,
  },
  {
    id: 'designations',
    label: 'Designations',
    path: '/designations',
    icon: 'BriefcaseBusiness',
    module: 'Module 5',
    requiredPermission: PERMISSIONS.DESIGNATION_VIEW,
  },
  {
    id: 'attendance',
    label: 'Attendance',
    selfServiceLabel: 'My Attendance',
    path: '/attendance',
    icon: 'Clock3',
    module: 'Module 7',
    requiredPermission: PERMISSIONS.ATTENDANCE_VIEW,
  },
  {
    id: 'leave',
    label: 'Leave',
    selfServiceLabel: 'My Leave',
    path: '/leave',
    icon: 'CalendarDays',
    module: 'Module 8',
    requiredPermission: PERMISSIONS.LEAVE_VIEW,
  },
  {
    id: 'salary',
    label: 'Salary',
    selfServiceLabel: 'My Compensation',
    path: '/salary',
    icon: 'Wallet',
    module: 'Module 9',
    requiredPermission: PERMISSIONS.SALARY_VIEW,
  },
  {
    id: 'payroll',
    label: 'Payroll',
    path: '/payroll',
    icon: 'Banknote',
    module: 'Later module',
    requiredPermission: PERMISSIONS.PAYROLL_VIEW,
  },
  {
    id: 'payslips',
    label: 'Payslips',
    selfServiceLabel: 'My Payslips',
    path: '/payslips',
    icon: 'FileText',
    module: 'Later module',
    requiredPermission: PERMISSIONS.PAYSLIP_VIEW,
  },
  {
    id: 'reports',
    label: 'Reports',
    path: '/reports',
    icon: 'BarChart3',
    module: 'Later module',
    requiredPermission: PERMISSIONS.REPORTS_VIEW,
  },
  {
    id: 'notifications',
    label: 'Notifications',
    path: '/notifications',
    icon: 'Bell',
    module: 'Module 4',
    requiredPermission: PERMISSIONS.NOTIFICATION_VIEW,
  },
  {
    id: 'users',
    label: 'Users',
    path: '/users',
    icon: 'Shield',
    module: 'Later module',
    requiredPermission: PERMISSIONS.USER_VIEW,
  },
  {
    id: 'settings',
    label: 'Settings',
    path: '/settings',
    icon: 'Settings',
    module: 'Later module',
    requiredPermission: PERMISSIONS.SETTINGS_VIEW,
  },
  {
    id: 'profile',
    label: 'My Profile',
    path: '/profile',
    icon: 'UserRound',
    requiredPermission: PERMISSIONS.PROFILE_VIEW,
  },
]
