import type { NavigationItem } from '@/types'
import { PERMISSIONS } from './permissions'

export const NAVIGATION_ITEMS: NavigationItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    path: '/dashboard',
    selfServicePath: '/employee/dashboard',
    icon: 'LayoutDashboard',
    group: 'main',
    requiredPermission: PERMISSIONS.DASHBOARD_VIEW,
  },
  {
    id: 'employees',
    label: 'Employees',
    path: '/employees',
    icon: 'Users',
    group: 'people',
    requiredPermission: PERMISSIONS.EMPLOYEE_VIEW,
  },
  {
    id: 'departments',
    label: 'Departments',
    path: '/departments',
    icon: 'Building2',
    group: 'people',
    requiredPermission: PERMISSIONS.DEPARTMENT_VIEW,
  },
  {
    id: 'designations',
    label: 'Designations',
    path: '/designations',
    icon: 'BriefcaseBusiness',
    group: 'people',
    requiredPermission: PERMISSIONS.DESIGNATION_VIEW,
  },
  {
    id: 'attendance',
    label: 'Attendance',
    selfServiceLabel: 'My Attendance',
    path: '/attendance',
    selfServicePath: '/employee/attendance',
    icon: 'Clock3',
    group: 'people',
    requiredPermission: PERMISSIONS.ATTENDANCE_VIEW,
  },
  {
    id: 'leave',
    label: 'Leave',
    selfServiceLabel: 'My Leave',
    path: '/leave',
    selfServicePath: '/employee/leave',
    icon: 'CalendarDays',
    group: 'people',
    requiredPermission: PERMISSIONS.LEAVE_VIEW,
  },
  {
    id: 'salary',
    label: 'Salary',
    selfServiceLabel: 'My Compensation',
    path: '/salary',
    selfServicePath: '/employee/salary',
    icon: 'Wallet',
    group: 'payroll',
    requiredPermission: PERMISSIONS.SALARY_VIEW,
  },
  {
    id: 'payroll',
    label: 'Payroll',
    path: '/payroll',
    icon: 'Banknote',
    group: 'payroll',
    requiredPermission: PERMISSIONS.PAYROLL_VIEW,
  },
  {
    id: 'payslips',
    label: 'Payslips',
    selfServiceLabel: 'My Payslips',
    path: '/payslips',
    selfServicePath: '/employee/payslips',
    icon: 'FileText',
    group: 'payroll',
    requiredPermission: PERMISSIONS.PAYSLIP_VIEW,
  },
  {
    id: 'reports',
    label: 'Reports',
    path: '/reports',
    icon: 'BarChart3',
    group: 'management',
    requiredPermission: PERMISSIONS.REPORTS_VIEW,
  },
  {
    id: 'users',
    label: 'Users',
    path: '/users',
    icon: 'UserCog',
    group: 'management',
    requiredPermission: PERMISSIONS.USER_VIEW,
  },
  {
    id: 'roles',
    label: 'Roles',
    path: '/roles',
    icon: 'Shield',
    group: 'management',
    requiredPermission: PERMISSIONS.ROLE_VIEW,
  },
  {
    id: 'permissions',
    label: 'Permissions',
    path: '/permissions',
    icon: 'KeyRound',
    group: 'management',
    requiredPermission: PERMISSIONS.PERMISSION_VIEW,
  },
  {
    id: 'workflows',
    label: 'Workflows',
    path: '/workflows',
    icon: 'RefreshCw',
    group: 'system',
    requiredPermission: PERMISSIONS.WORKFLOW_VIEW,
  },
  {
    id: 'notifications',
    label: 'Notifications',
    path: '/notifications',
    selfServicePath: '/employee/notifications',
    icon: 'Bell',
    group: 'system',
    requiredPermission: PERMISSIONS.NOTIFICATION_VIEW,
  },
  {
    id: 'settings',
    label: 'Settings',
    path: '/settings',
    icon: 'Settings',
    group: 'system',
    requiredPermission: PERMISSIONS.SETTINGS_VIEW,
  },
  {
    id: 'security',
    label: 'Security',
    path: '/security',
    icon: 'ShieldCheck',
    group: 'system',
    requiredPermission: PERMISSIONS.SECURITY_VIEW,
  },
  {
    id: 'profile',
    label: 'My Profile',
    path: '/profile',
    selfServicePath: '/employee/profile',
    icon: 'UserRound',
    group: 'account',
    requiredPermission: PERMISSIONS.PROFILE_VIEW,
  },
]

export const ESS_NAVIGATION_ITEMS: NavigationItem[] = [
  {
    id: 'ess-dashboard',
    label: 'Dashboard',
    path: '/employee/dashboard',
    selfServicePath: '/employee/dashboard',
    icon: 'LayoutDashboard',
    group: 'main',
    requiredPermission: PERMISSIONS.ESS_VIEW,
  },
  {
    id: 'ess-profile',
    label: 'My Profile',
    path: '/employee/profile',
    selfServicePath: '/employee/profile',
    icon: 'UserRound',
    group: 'main',
    requiredPermission: PERMISSIONS.PROFILE_VIEW,
  },
  {
    id: 'ess-attendance',
    label: 'Attendance',
    path: '/employee/attendance',
    selfServicePath: '/employee/attendance',
    icon: 'Clock3',
    group: 'people',
    requiredPermission: PERMISSIONS.ATTENDANCE_VIEW,
  },
  {
    id: 'ess-leave',
    label: 'Leave',
    path: '/employee/leave',
    selfServicePath: '/employee/leave',
    icon: 'CalendarDays',
    group: 'people',
    requiredPermission: PERMISSIONS.LEAVE_VIEW,
  },
  {
    id: 'ess-salary',
    label: 'Salary',
    path: '/employee/salary',
    selfServicePath: '/employee/salary',
    icon: 'Wallet',
    group: 'payroll',
    requiredPermission: PERMISSIONS.SALARY_VIEW,
  },
  {
    id: 'ess-payslips',
    label: 'Payslips',
    path: '/employee/payslips',
    selfServicePath: '/employee/payslips',
    icon: 'FileText',
    group: 'payroll',
    requiredPermission: PERMISSIONS.PAYSLIP_VIEW,
  },
  {
    id: 'ess-documents',
    label: 'Documents',
    path: '/employee/documents',
    selfServicePath: '/employee/documents',
    icon: 'FolderOpen',
    group: 'people',
    requiredPermission: PERMISSIONS.ESS_VIEW,
  },
  {
    id: 'ess-requests',
    label: 'Requests',
    path: '/employee/requests',
    selfServicePath: '/employee/requests',
    icon: 'ClipboardList',
    group: 'people',
    requiredPermission: PERMISSIONS.ESS_VIEW,
  },
  {
    id: 'ess-notifications',
    label: 'Notifications',
    path: '/employee/notifications',
    selfServicePath: '/employee/notifications',
    icon: 'Bell',
    group: 'system',
    requiredPermission: PERMISSIONS.NOTIFICATION_VIEW,
  },
  {
    id: 'ess-settings',
    label: 'Settings',
    path: '/employee/settings',
    selfServicePath: '/employee/settings',
    icon: 'Settings',
    group: 'system',
    requiredPermission: PERMISSIONS.ESS_VIEW,
  },
]
