import type { PermissionName } from '@/types'

export const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard.view',
  PROFILE_VIEW: 'profile.view',
  PROFILE_EDIT: 'profile.edit',
  EMPLOYEE_VIEW: 'employee.view',
  EMPLOYEE_CREATE: 'employee.create',
  EMPLOYEE_EDIT: 'employee.edit',
  EMPLOYEE_DELETE: 'employee.delete',
  EMPLOYEE_MANAGE: 'employee.manage',
  EMPLOYEE_EXPORT: 'employee.export',
  DEPARTMENT_VIEW: 'department.view',
  DEPARTMENT_CREATE: 'department.create',
  DEPARTMENT_EDIT: 'department.edit',
  DEPARTMENT_DELETE: 'department.delete',
  DEPARTMENT_MANAGE: 'department.manage',
  DESIGNATION_VIEW: 'designation.view',
  DESIGNATION_CREATE: 'designation.create',
  DESIGNATION_EDIT: 'designation.edit',
  DESIGNATION_DELETE: 'designation.delete',
  DESIGNATION_MANAGE: 'designation.manage',
  ATTENDANCE_VIEW: 'attendance.view',
  ATTENDANCE_CREATE: 'attendance.create',
  ATTENDANCE_EDIT: 'attendance.edit',
  ATTENDANCE_MANAGE: 'attendance.manage',
  ATTENDANCE_CORRECT: 'attendance.correct',
  ATTENDANCE_APPROVE: 'attendance.approve',
  ATTENDANCE_EXPORT: 'attendance.export',
  LEAVE_VIEW: 'leave.view',
  LEAVE_CREATE: 'leave.create',
  LEAVE_APPLY: 'leave.apply',
  LEAVE_EDIT: 'leave.edit',
  LEAVE_CANCEL: 'leave.cancel',
  LEAVE_APPROVE: 'leave.approve',
  LEAVE_REJECT: 'leave.reject',
  LEAVE_MANAGE: 'leave.manage',
  LEAVE_TYPE_MANAGE: 'leave.type.manage',
  LEAVE_BALANCE_MANAGE: 'leave.balance.manage',
  LEAVE_EXPORT: 'leave.export',
  SALARY_VIEW: 'salary.view',
  SALARY_CREATE: 'salary.create',
  SALARY_EDIT: 'salary.edit',
  SALARY_DELETE: 'salary.delete',
  SALARY_MANAGE: 'salary.manage',
  SALARY_ASSIGN: 'salary.assign',
  SALARY_REVISE: 'salary.revise',
  SALARY_COMPONENT_MANAGE: 'salary.component.manage',
  SALARY_EXPORT: 'salary.export',
  PAYROLL_VIEW: 'payroll.view',
  PAYROLL_CREATE: 'payroll.create',
  PAYROLL_EDIT: 'payroll.edit',
  PAYROLL_CALCULATE: 'payroll.calculate',
  PAYROLL_PROCESS: 'payroll.process',
  PAYROLL_APPROVE: 'payroll.approve',
  PAYROLL_REJECT: 'payroll.reject',
  PAYROLL_DELETE: 'payroll.delete',
  PAYROLL_MANAGE: 'payroll.manage',
  PAYROLL_SETTINGS_MANAGE: 'payroll.settings.manage',
  PAYROLL_EMPLOYEE_VIEW: 'payroll.employee.view',
  PAYROLL_FINALIZE: 'payroll.finalize',
  PAYROLL_EXPORT: 'payroll.export',
  PAYSLIP_VIEW: 'payslip.view',
  PAYSLIP_GENERATE: 'payslip.generate',
  PAYSLIP_PRINT: 'payslip.print',
  PAYSLIP_DOWNLOAD: 'payslip.download',
  PAYSLIP_MANAGE: 'payslip.manage',
  REPORTS_VIEW: 'report.view',
  REPORT_EMPLOYEE: 'report.employee',
  REPORT_ATTENDANCE: 'report.attendance',
  REPORT_LEAVE: 'report.leave',
  REPORT_SALARY: 'report.salary',
  REPORT_PAYROLL: 'report.payroll',
  REPORT_PAYSLIP: 'report.payslip',
  REPORT_DEPARTMENT: 'report.department',
  REPORT_WORKFORCE: 'report.workforce',
  REPORT_EXPORT: 'report.export',
  REPORT_ADMIN: 'report.admin',
  NOTIFICATION_VIEW: 'notification.view',
  NOTIFICATION_MANAGE: 'notification.manage',
  NOTIFICATION_TEMPLATE_MANAGE: 'notification.template.manage',
  NOTIFICATION_SETTINGS_MANAGE: 'notification.settings.manage',
  WORKFLOW_VIEW: 'workflow.view',
  WORKFLOW_CREATE: 'workflow.create',
  WORKFLOW_APPROVE: 'workflow.approve',
  WORKFLOW_REJECT: 'workflow.reject',
  WORKFLOW_MANAGE: 'workflow.manage',
  WORKFLOW_ADMIN: 'workflow.admin',
  USER_VIEW: 'user.view',
  USER_CREATE: 'user.create',
  USER_EDIT: 'user.edit',
  USER_DELETE: 'user.delete',
  USER_MANAGE: 'user.manage',
  USER_EXPORT: 'user.export',
  ROLE_VIEW: 'role.view',
  ROLE_CREATE: 'role.create',
  ROLE_EDIT: 'role.edit',
  ROLE_DELETE: 'role.delete',
  ROLE_MANAGE: 'role.manage',
  PERMISSION_VIEW: 'permission.view',
  PERMISSION_MANAGE: 'permission.manage',
  SECURITY_VIEW: 'security.view',
  SECURITY_MANAGE: 'security.manage',
  SETTINGS_VIEW: 'settings.view',
  SETTINGS_MANAGE: 'settings.manage',
  COMPANY_MANAGE: 'company.manage',
  ORGANIZATION_MANAGE: 'organization.manage',
  LOCATION_MANAGE: 'location.manage',
  SCHEDULE_MANAGE: 'schedule.manage',
  HOLIDAY_MANAGE: 'holiday.manage',
  LEAVE_POLICY_MANAGE: 'leave-policy.manage',
  ATTENDANCE_SETTINGS_MANAGE: 'attendance-settings.manage',
  PAYROLL_SETTINGS_MANAGE_GLOBAL: 'payroll-settings.manage',
  PAYSLIP_SETTINGS_MANAGE: 'payslip-settings.manage',
  LOCALIZATION_MANAGE: 'localization.manage',
  BRANDING_MANAGE: 'branding.manage',
  NOTIFICATION_SETTINGS_MANAGE_GLOBAL: 'notification-settings.manage',
  WORKFLOW_SETTINGS_MANAGE: 'workflow-settings.manage',
  ESS_VIEW: 'ess.view',
} as const satisfies Record<string, PermissionName>

export const ALL_PERMISSIONS: PermissionName[] = Object.values(PERMISSIONS)

/** Permissions that require an extra confirmation when granting. */
export const DANGEROUS_PERMISSIONS: PermissionName[] = [
  PERMISSIONS.PAYROLL_FINALIZE,
  PERMISSIONS.PAYROLL_MANAGE,
  PERMISSIONS.SALARY_MANAGE,
  PERMISSIONS.USER_MANAGE,
  PERMISSIONS.ROLE_MANAGE,
  PERMISSIONS.PERMISSION_MANAGE,
  PERMISSIONS.SETTINGS_MANAGE,
]

/** Simple permission dependencies: granting key requires value. */
export const PERMISSION_DEPENDENCIES: Partial<Record<PermissionName, PermissionName[]>> = {
  [PERMISSIONS.EMPLOYEE_EDIT]: [PERMISSIONS.EMPLOYEE_VIEW],
  [PERMISSIONS.EMPLOYEE_DELETE]: [PERMISSIONS.EMPLOYEE_VIEW],
  [PERMISSIONS.EMPLOYEE_EXPORT]: [PERMISSIONS.EMPLOYEE_VIEW],
  [PERMISSIONS.ATTENDANCE_MANAGE]: [PERMISSIONS.ATTENDANCE_VIEW],
  [PERMISSIONS.ATTENDANCE_APPROVE]: [PERMISSIONS.ATTENDANCE_VIEW],
  [PERMISSIONS.ATTENDANCE_EXPORT]: [PERMISSIONS.ATTENDANCE_VIEW],
  [PERMISSIONS.LEAVE_APPROVE]: [PERMISSIONS.LEAVE_VIEW],
  [PERMISSIONS.LEAVE_REJECT]: [PERMISSIONS.LEAVE_VIEW],
  [PERMISSIONS.LEAVE_MANAGE]: [PERMISSIONS.LEAVE_VIEW],
  [PERMISSIONS.LEAVE_EXPORT]: [PERMISSIONS.LEAVE_VIEW],
  [PERMISSIONS.SALARY_MANAGE]: [PERMISSIONS.SALARY_VIEW],
  [PERMISSIONS.SALARY_EXPORT]: [PERMISSIONS.SALARY_VIEW],
  [PERMISSIONS.PAYROLL_APPROVE]: [PERMISSIONS.PAYROLL_VIEW],
  [PERMISSIONS.PAYROLL_FINALIZE]: [PERMISSIONS.PAYROLL_VIEW],
  [PERMISSIONS.PAYROLL_EXPORT]: [PERMISSIONS.PAYROLL_VIEW],
  [PERMISSIONS.PAYSLIP_GENERATE]: [PERMISSIONS.PAYSLIP_VIEW],
  [PERMISSIONS.REPORT_EXPORT]: [PERMISSIONS.REPORTS_VIEW],
  [PERMISSIONS.USER_EDIT]: [PERMISSIONS.USER_VIEW],
  [PERMISSIONS.USER_MANAGE]: [PERMISSIONS.USER_VIEW],
  [PERMISSIONS.ROLE_EDIT]: [PERMISSIONS.ROLE_VIEW],
  [PERMISSIONS.ROLE_MANAGE]: [PERMISSIONS.ROLE_VIEW],
  [PERMISSIONS.PERMISSION_MANAGE]: [PERMISSIONS.PERMISSION_VIEW],
}
