import type { PermissionName, RoleName } from '@/types'
import { ALL_PERMISSIONS, PERMISSIONS } from './permissions'
import { ROLES } from './roles'

export const ROLE_PERMISSIONS: Record<RoleName, PermissionName[]> = {
  [ROLES.SUPER_ADMIN]: [...ALL_PERMISSIONS],

  [ROLES.HR_ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_EDIT,
    PERMISSIONS.EMPLOYEE_VIEW,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_EDIT,
    PERMISSIONS.EMPLOYEE_DELETE,
    PERMISSIONS.EMPLOYEE_MANAGE,
    PERMISSIONS.DEPARTMENT_VIEW,
    PERMISSIONS.DEPARTMENT_CREATE,
    PERMISSIONS.DEPARTMENT_EDIT,
    PERMISSIONS.DEPARTMENT_DELETE,
    PERMISSIONS.DEPARTMENT_MANAGE,
    PERMISSIONS.DESIGNATION_VIEW,
    PERMISSIONS.DESIGNATION_CREATE,
    PERMISSIONS.DESIGNATION_EDIT,
    PERMISSIONS.DESIGNATION_DELETE,
    PERMISSIONS.DESIGNATION_MANAGE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_CREATE,
    PERMISSIONS.ATTENDANCE_EDIT,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.ATTENDANCE_CORRECT,
    PERMISSIONS.ATTENDANCE_APPROVE,
    PERMISSIONS.LEAVE_VIEW,
    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.LEAVE_EDIT,
    PERMISSIONS.LEAVE_CANCEL,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.LEAVE_REJECT,
    PERMISSIONS.LEAVE_MANAGE,
    PERMISSIONS.LEAVE_TYPE_MANAGE,
    PERMISSIONS.LEAVE_BALANCE_MANAGE,
    PERMISSIONS.PAYROLL_VIEW,
    PERMISSIONS.PAYROLL_MANAGE,
    PERMISSIONS.PAYSLIP_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.NOTIFICATION_MANAGE,
    PERMISSIONS.USER_VIEW,
    // Intentionally excludes settings.manage and user create/edit/delete
    // and does not grant Super Admin exclusive controls.
  ],

  [ROLES.EMPLOYEE]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_EDIT,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.LEAVE_VIEW,
    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.LEAVE_EDIT,
    PERMISSIONS.LEAVE_CANCEL,
    PERMISSIONS.PAYSLIP_VIEW,
    PERMISSIONS.NOTIFICATION_VIEW,
  ],
}

export function getPermissionsForRole(role: RoleName): PermissionName[] {
  return ROLE_PERMISSIONS[role] ?? []
}
