import type { PermissionName, RoleName } from '@/types'
import { ALL_PERMISSIONS, PERMISSIONS } from './permissions'
import { ROLES } from './roles'

const ESS_BASE: PermissionName[] = [
  PERMISSIONS.DASHBOARD_VIEW,
  PERMISSIONS.PROFILE_VIEW,
  PERMISSIONS.PROFILE_EDIT,
  PERMISSIONS.ATTENDANCE_VIEW,
  PERMISSIONS.LEAVE_VIEW,
  PERMISSIONS.LEAVE_CREATE,
  PERMISSIONS.LEAVE_APPLY,
  PERMISSIONS.LEAVE_EDIT,
  PERMISSIONS.LEAVE_CANCEL,
  PERMISSIONS.SALARY_VIEW,
  PERMISSIONS.PAYSLIP_VIEW,
  PERMISSIONS.NOTIFICATION_VIEW,
  PERMISSIONS.WORKFLOW_VIEW,
  PERMISSIONS.ESS_VIEW,
]

const MANAGER_PERMS: PermissionName[] = [
  ...ESS_BASE,
  PERMISSIONS.EMPLOYEE_VIEW,
  PERMISSIONS.DEPARTMENT_VIEW,
  PERMISSIONS.DESIGNATION_VIEW,
  PERMISSIONS.ATTENDANCE_CREATE,
  PERMISSIONS.ATTENDANCE_EDIT,
  PERMISSIONS.ATTENDANCE_APPROVE,
  PERMISSIONS.LEAVE_APPROVE,
  PERMISSIONS.LEAVE_REJECT,
  PERMISSIONS.WORKFLOW_APPROVE,
  PERMISSIONS.WORKFLOW_REJECT,
  PERMISSIONS.WORKFLOW_CREATE,
]

const HR_MANAGER_PERMS: PermissionName[] = [
  ...MANAGER_PERMS,
  PERMISSIONS.EMPLOYEE_CREATE,
  PERMISSIONS.EMPLOYEE_EDIT,
  PERMISSIONS.EMPLOYEE_MANAGE,
  PERMISSIONS.ATTENDANCE_MANAGE,
  PERMISSIONS.ATTENDANCE_CORRECT,
  PERMISSIONS.LEAVE_MANAGE,
  PERMISSIONS.LEAVE_TYPE_MANAGE,
  PERMISSIONS.LEAVE_BALANCE_MANAGE,
  PERMISSIONS.REPORTS_VIEW,
  PERMISSIONS.REPORT_EMPLOYEE,
  PERMISSIONS.REPORT_ATTENDANCE,
  PERMISSIONS.REPORT_LEAVE,
  PERMISSIONS.REPORT_DEPARTMENT,
  PERMISSIONS.REPORT_WORKFORCE,
  PERMISSIONS.REPORT_EXPORT,
  PERMISSIONS.NOTIFICATION_MANAGE,
  PERMISSIONS.WORKFLOW_MANAGE,
  PERMISSIONS.USER_VIEW,
  // Intentionally excludes salary.manage / payroll.finalize by default
]

const HR_ADMIN_PERMS: PermissionName[] = [
  ...HR_MANAGER_PERMS,
  PERMISSIONS.EMPLOYEE_DELETE,
  PERMISSIONS.EMPLOYEE_EXPORT,
  PERMISSIONS.DEPARTMENT_CREATE,
  PERMISSIONS.DEPARTMENT_EDIT,
  PERMISSIONS.DEPARTMENT_DELETE,
  PERMISSIONS.DEPARTMENT_MANAGE,
  PERMISSIONS.DESIGNATION_CREATE,
  PERMISSIONS.DESIGNATION_EDIT,
  PERMISSIONS.DESIGNATION_DELETE,
  PERMISSIONS.DESIGNATION_MANAGE,
  PERMISSIONS.ATTENDANCE_EXPORT,
  PERMISSIONS.LEAVE_EXPORT,
  PERMISSIONS.SALARY_VIEW,
  PERMISSIONS.SALARY_CREATE,
  PERMISSIONS.SALARY_EDIT,
  PERMISSIONS.SALARY_DELETE,
  PERMISSIONS.SALARY_MANAGE,
  PERMISSIONS.SALARY_ASSIGN,
  PERMISSIONS.SALARY_REVISE,
  PERMISSIONS.SALARY_COMPONENT_MANAGE,
  PERMISSIONS.SALARY_EXPORT,
  PERMISSIONS.PAYROLL_VIEW,
  PERMISSIONS.PAYROLL_CREATE,
  PERMISSIONS.PAYROLL_EDIT,
  PERMISSIONS.PAYROLL_CALCULATE,
  PERMISSIONS.PAYROLL_PROCESS,
  PERMISSIONS.PAYROLL_APPROVE,
  PERMISSIONS.PAYROLL_REJECT,
  PERMISSIONS.PAYROLL_DELETE,
  PERMISSIONS.PAYROLL_MANAGE,
  PERMISSIONS.PAYROLL_SETTINGS_MANAGE,
  PERMISSIONS.PAYROLL_EMPLOYEE_VIEW,
  PERMISSIONS.PAYROLL_FINALIZE,
  PERMISSIONS.PAYROLL_EXPORT,
  PERMISSIONS.PAYSLIP_GENERATE,
  PERMISSIONS.PAYSLIP_PRINT,
  PERMISSIONS.PAYSLIP_DOWNLOAD,
  PERMISSIONS.PAYSLIP_MANAGE,
  PERMISSIONS.REPORT_SALARY,
  PERMISSIONS.REPORT_PAYROLL,
  PERMISSIONS.REPORT_PAYSLIP,
  PERMISSIONS.NOTIFICATION_TEMPLATE_MANAGE,
  PERMISSIONS.NOTIFICATION_SETTINGS_MANAGE,
  PERMISSIONS.USER_CREATE,
  PERMISSIONS.USER_EDIT,
  PERMISSIONS.USER_EXPORT,
  PERMISSIONS.ROLE_VIEW,
  PERMISSIONS.SECURITY_VIEW,
  // Excludes user.manage, role.manage, permission.manage, settings.manage
]

export const ROLE_PERMISSIONS: Record<RoleName, PermissionName[]> = {
  [ROLES.SUPER_ADMIN]: [...ALL_PERMISSIONS],
  [ROLES.HR_ADMIN]: HR_ADMIN_PERMS,
  [ROLES.HR_MANAGER]: HR_MANAGER_PERMS,
  [ROLES.MANAGER]: MANAGER_PERMS,
  [ROLES.EMPLOYEE]: ESS_BASE,
}

/** Mutable overrides applied by Super Admin via Role Management UI. */
const rolePermissionOverrides = new Map<RoleName, PermissionName[]>()

export function setRolePermissionOverride(role: RoleName, permissions: PermissionName[]): void {
  rolePermissionOverrides.set(role, [...new Set(permissions)])
}

export function clearRolePermissionOverride(role: RoleName): void {
  rolePermissionOverrides.delete(role)
}

export function getPermissionsForRole(role: RoleName): PermissionName[] {
  return rolePermissionOverrides.get(role) ?? ROLE_PERMISSIONS[role] ?? []
}
