export {
  EssAttendanceCalendarPage,
  EssAttendancePage,
  EssDashboardPage,
  EssDocumentsPage,
  EssLeaveApplyPage,
  EssLeaveDetailPage,
  EssLeavePage,
  EssNotificationsPage,
  EssPayslipDetailPage,
  EssPayslipsPage,
  EssProfilePage,
  EssRequestDetailPage,
  EssRequestsPage,
  EssSalaryPage,
  EssSettingsPage,
} from './EssPages'
