export const NOTIFICATION_EVENTS = {
  LEAVE_SUBMITTED: 'LEAVE_SUBMITTED',
  LEAVE_APPROVED: 'LEAVE_APPROVED',
  LEAVE_REJECTED: 'LEAVE_REJECTED',
  ATTENDANCE_CORRECTION_SUBMITTED: 'ATTENDANCE_CORRECTION_SUBMITTED',
  ATTENDANCE_CORRECTION_APPROVED: 'ATTENDANCE_CORRECTION_APPROVED',
  ATTENDANCE_CORRECTION_REJECTED: 'ATTENDANCE_CORRECTION_REJECTED',
  PROFILE_CHANGE_SUBMITTED: 'PROFILE_CHANGE_SUBMITTED',
  PROFILE_CHANGE_APPROVED: 'PROFILE_CHANGE_APPROVED',
  PROFILE_CHANGE_REJECTED: 'PROFILE_CHANGE_REJECTED',
  PAYROLL_SUBMITTED: 'PAYROLL_SUBMITTED',
  PAYROLL_APPROVED: 'PAYROLL_APPROVED',
  PAYROLL_REJECTED: 'PAYROLL_REJECTED',
  PAYROLL_FINALIZED: 'PAYROLL_FINALIZED',
  PAYSLIP_GENERATED: 'PAYSLIP_GENERATED',
  WORKFLOW_ASSIGNED: 'WORKFLOW_ASSIGNED',
  WORKFLOW_NEEDS_INFORMATION: 'WORKFLOW_NEEDS_INFORMATION',
  ANNOUNCEMENT_PUBLISHED: 'ANNOUNCEMENT_PUBLISHED',
} as const

export type NotificationEventCode =
  (typeof NOTIFICATION_EVENTS)[keyof typeof NOTIFICATION_EVENTS]
