import { PERMISSIONS } from '@/constants/permissions'
import type { ReportDefinition } from './types'

export const REPORT_DEFINITIONS: ReportDefinition[] = [
  {
    id: 'overview',
    name: 'Overview',
    description: 'Executive KPIs across workforce, attendance, leave, payroll, and payslips.',
    route: '/reports/overview',
    permission: PERMISSIONS.REPORTS_VIEW,
    category: 'workforce',
  },
  {
    id: 'employees',
    name: 'Employee Report',
    description: 'Directory status, joining trends, department distribution, and new joiners.',
    route: '/reports/employees',
    permission: PERMISSIONS.REPORT_EMPLOYEE,
    category: 'workforce',
  },
  {
    id: 'attendance',
    name: 'Attendance Report',
    description: 'Monthly attendance percentage, late arrivals, absences, and employee summaries.',
    route: '/reports/attendance',
    permission: PERMISSIONS.REPORT_ATTENDANCE,
    category: 'attendance',
  },
  {
    id: 'leave',
    name: 'Leave Report',
    description: 'Leave request status, leave type mix, usage, and employee balances.',
    route: '/reports/leave',
    permission: PERMISSIONS.REPORT_LEAVE,
    category: 'leave',
  },
  {
    id: 'salary',
    name: 'Salary Report',
    description: 'Salary assignments and compensation totals grouped safely by currency.',
    route: '/reports/salary',
    permission: PERMISSIONS.REPORT_SALARY,
    category: 'payroll',
  },
  {
    id: 'payroll',
    name: 'Payroll Report',
    description: 'Payroll run totals, trends, statuses, and department summary for selected runs.',
    route: '/reports/payroll',
    permission: PERMISSIONS.REPORT_PAYROLL,
    category: 'payroll',
  },
  {
    id: 'payslips',
    name: 'Payslip Report',
    description: 'Payslip generation status, employee payslip rows, and currency-specific totals.',
    route: '/reports/payslips',
    permission: PERMISSIONS.REPORT_PAYSLIP,
    category: 'payroll',
  },
  {
    id: 'departments',
    name: 'Department Report',
    description: 'Department roster counts, heads, locations, and active distribution.',
    route: '/reports/departments',
    permission: PERMISSIONS.REPORT_DEPARTMENT,
    category: 'workforce',
  },
  {
    id: 'designations',
    name: 'Designation Report',
    description: 'Designation distribution by level, department, and active employee count.',
    route: '/reports/designations',
    permission: PERMISSIONS.REPORT_DEPARTMENT,
    category: 'workforce',
  },
  {
    id: 'workforce',
    name: 'Workforce Analytics',
    description: 'Headcount analytics by employment type, tenure, department, and salary ranges.',
    route: '/reports/workforce',
    permission: PERMISSIONS.REPORT_WORKFORCE,
    category: 'workforce',
  },
]
